### ISSUE TITLE
Ongoing project cleanup

### ISSUE THREAD

**Issue by pmdartus** [salesforce/lwc#104]
### Description

This issue list ongoing cleanup work items to keep this project clean and improve the overall developer productivity. Don't hesitate to pick up one of those work items between when you get bored. 💃 

#### Legend

| Effort | Icon  |
|------|---|
| Low |  ✳️  |
| Medium |  🔶  |
| High |  🔴  |

#### Done

* [x] ✳️ - Remove `.eslintrc` and `.eslintignore` from the root directory
* [x] ✳️ - Update outdated dev dependencies. Good candidates: `jest`, `typescript`, `rollup`, `tslint`, `ts-jest` (run `yarn outdated` in the root directory to list all the outdated dependencies).
* [x] ✳️ - Remove `packages/README.md`.
* [X] ✳️ - Update `README.md` and `CONTRIBUTING.md` to match current developement workflow
* [x] 🔶 - Remove `power-assert` and `mocha` in the remaing package in the favor of `jest`
* [x] 🔶 - Remove `eslint` from packages using typescript in favor of `ts-lint`
* [x] 🔶 - Share with all the projects `tslint.config`
* [x] 🔶 - Run linting on the CI
* [X] 🔶 - Make the `lwc-engine` unit test less verbose (Issue: #94)
* [x] 🔴 - Stabilize IE11 compat integration test (Issue: #95, PR: #103)
* [X] 🔴 - Add prettier to the repo (PR: #1057)
