### ISSUE TITLE
synthetic shadow polyfill

### ISSUE THREAD

**Issue by caridy** [salesforce/lwc#1164]
## Tasks

* [x] ([in-progress](https://github.com/salesforce/lwc/pull/1157)) moving all shadow dom related polyfills into `@lwc/synthetic-shadow` new pkg
* [x] refactor `patch.ts` to completely disconnect from polyfill. This includes:
  - [x] enabling appendChild and co in ShadowRoot
  - [x] change engine to use dot notation for the diffing algo instead of cached low level operations (~~this will represent a perf regression for sure~~ turns out that it doesn't)
  - [ ] implement slotting manually in situ instead of the pre-allocation that we use today (that will make things slower as well... but will solve all the issues that we have with the connect/disconnect non-sense for slotted content.
  - [x] refactor patching of node protos to be done in the polyfill instead of part of the diffing algo.
  - [ ] need a different mechanism to allow `lwc:dom=manual`, the current one is a hard connecting between engine and polyfill.
* [x] change the distribution of the engine to NOT include the synthetic shadow out of the box, instead it should be included manually ahead of time.
   - [ ] change all apps (everybody)
   - [ ] change aura distro (@diervo)
   - [ ] change playground (@midzelis)
   - [ ] change jest tools (@trevor-bliss)
* [ ] consider removing the mutation observer in favor of a different mechanism to detect insertion and removal of non-registered custom elements across the board:
   - [ ] refactor `upgrade.ts` and `wc.ts` to rely on a different mechanism to detect insertion/removal
   - [ ] this will probably be another perf regression (review), but might help on the overall picture.
* [ ] some other cleanup
   - [ ] the presumption that compiler could provide specific hooks when detecting no-attribute, no-events, etc... seems wrong after some perf tests in the past, maybe we can remove that provision all together from engine/diffing
