### ISSUE TITLE
Transition to the new decorate syntax for component decorators

### ISSUE THREAD

**Issue by pmdartus** [salesforce/lwc#332]
### Description

Today the babel plugin transforms the decorators to static properties on the class. We recently introduced the `decorate` API in the engine (https://github.com/salesforce/lwc/pull/280) to be able to use the decorators without needing the transformation set.

### Tasks

* [ ] Update the babel transform to emit code using the `decorate` API
* [ ] Update all the unit-test to leverage the `decorate` API
* [x] Remove code related to static properties in the engine

**Comment by jmsjtu** [comment]
We should eventually remove the decorator transformation and use the native [decorator proposal](https://github.com/tc39/proposal-decorators) (currently stage 3)

**Comment by caridy** [comment]
@jmsjtu the question is really how much work is this going to be.
