### ISSUE TITLE
[compiler] only the getter or setter can be decorator

### ISSUE THREAD

**Issue by caridy** [salesforce/lwc#436]
### Description

Today, our implementation of decorators diverged from the spec. We ask devs to add the decorator to the getter and setter alike, otherwise we throw an error.

This is incompatible with the decorator semantics which describes that a decorator can only be applied once to a descriptor.

#### TODO:

 * [x] add compiler warning for the restriction back still allow @api in both
 * [x] implement the new semantics (change the restriction to allow @api only in one of them)
 * [x] implement code-mod that can change all existing components to comply with the new rules.
